### PR TITLE
Add the missing export of the toMatchElement assertion

### PR DESCRIPTION
**Pull request by vkrol**

### CODE REVIEW

**Comment by blainekasten** [comment]
Whoa. @vkrol does this really mean that an error occurs if you try and use that matcher? I'm surprised this passed through.

**Comment by vkrol** [comment]
@blainekasten yes :)

**Comment by blainekasten** [comment]
Dang. I'll cut a release immediately

**Comment by vkrol** [comment]
@blainekasten thanks!

**Pull request merged**
