### PR TITLE
fix bug where stringify was mutating array values

### LINKED ISSUE #101: `toHaveProp()` modifies parameter value
Strangely the [`toHaveProp`](https://github.com/blainekasten/enzyme-matchers#tohaveproppropkeystring-propvalueany) matcher seems to modify the passed array value: 

```
it('check props', () => {
    const numberArray = [1, 2, 3];
    console.log(numberArray);                           // [ 1, 2, 3 ]
    expect(wrapper).toHaveProp('records', numberArray);
    console.log(numberArray);                           // [ 1 ]
});
```

I'm (apart from that happily 👍 ) using jasmine-enzyme 3.2.0 (and enzyme 2.8.2).

### PR DESCRIPTION
**Pull request by moredip**
This resolves #101

### CODE REVIEW

**Comment by blainekasten** [comment]
Can you add a test that proves we aren't manipulating arguments? should be something like this:

```
const props = [1, 2];
expect(wrapper).toHaveProps('foo', props);

// Then
expect(props).toEqual([1, 2]);
```

**Comment by moredip** [comment]
I went for a more focused test on `stringify` itself. Hope that's OK. Happy to write a more integrated test if you'd prefer.

**Comment by blainekasten** [comment]
Mind squashing your commit down to 1 and i'll merge! Thanks!

**Comment by moredip** [comment]
I'm on my phone so can't do it right now. When you merge the PR GitHub
should give you the option to squash.

**Comment by blainekasten** [comment]
@moredip it does, but then it includes me as part of the commit history. Would rather leave it for you. It's nit picky but I can wait until you have a chance

**Comment by moredip** [comment]
Gotcha, makes sense. Squash is now squished.

**Comment by moredip** [comment]
@blainekasten thanks muchly for accepting this. Any idea on timeline for a new release getting published? I would love to resolve the mutation issue in my app tests which led me here.

**Comment by blainekasten** [comment]
3.4.0 is released now!

**Pull request merged**
