### PR TITLE
fix type definition for jest-enzyme

### PR DESCRIPTION
**Pull request by cyberhck**
make type definition more accurate and comply with jest's type definition.

right now, when I try to define my own matcher, because of this type definition, I get an error: `All declarations of 'Matchers' must have identical type parameters`. Even though this doesn't use the R parameter, because all interfaces must have same type, this file gives everyone a hard time :)

### CODE REVIEW

**Comment by blainekasten** [comment]
Can you rebase master so I can merge?

**Comment by blainekasten** [comment]
Also, can you squash down to 1 commit?

**Comment by cyberhck** [comment]
I will rebase to master, can't we squash and merge from github's UI directly?

**Comment by cyberhck** [comment]
I did the rebase, please review.

**Comment by blainekasten** [comment]
@cyberhck can you squash to 1 commit please!

**Comment by cyberhck** [comment]
I couldn't get the merge commit to go away, is it fine if I remove this PR and make a new one?

**Comment by cyberhck** [comment]
closing in favor of #134

**Pull request closed without merging**
