### PR TITLE
Add types to package

### PR DESCRIPTION
**Pull request by lifeiscontent**
I'm not entirely sure if this will fix the issue with flow in #77 but, I suspect it will, I just haven't ever used lerna before and not sure how to test this locally.

please advise, thanks!

### CODE REVIEW

**Comment by blainekasten** [comment]
If I publish a pre-release version with this fix in could you test it?

**Comment by lifeiscontent** [comment]
@blainekasten I'd love to

**Comment by blainekasten** [comment]
Wait, couldn't you just use npm link locally to see if it resolves it for you? Can you try that first before I spend time making a pre-release?

**Comment by lifeiscontent** [comment]
@blainekasten I'm not sure if that would work due to lerna.

**Comment by lifeiscontent** [comment]
@blainekasten I actually tried to use `npm link` but it doesn't seem to work for me, or I don't know how to use it.

**Comment by blainekasten** [comment]
I just tested npm link locally and it should work. Here are the steps I did.

1. `cd` into `jest-enzyme` package. Not just the parent package
  - `cd enzyme-matchers/packages/jest-enzyme`
2. `npm link`
3. Go to application that uses jest-enzyme.
4. `npm link jest-enzyme`

Now the only thing to remember is that when you make changes, you need to rebuild jest-enzyme.

`npm run build`

**Comment by andriichernenko** [comment]
@blainekasten great news!

Any ETA on merging and shipping the changes?

**Comment by blainekasten** [comment]
I'm waiting on a confirmation that it fixes the problem. Once @lifeiscontent confirms I'll merge

**Comment by blainekasten** [comment]
I don't think this hurts to merge.. So i'm going to merge and if it doesn't fix it, we can come back to the drawing board.

**Comment by blainekasten** [comment]
woops.

**Comment by lifeiscontent** [comment]
@blainekasten I believe this is fixed, I'm no longer getting flow errors. Thanks!

**Comment by pascalduez** [comment]
Hi,

checking my `node_modules`, and although I'm up to date with the latest versions, there's no `types` folder in any of the packages.

**Comment by jfroom** [comment]
@pascalduez your issue sounds related to this? https://github.com/blainekasten/enzyme-matchers/issues/77

**Comment by pascalduez** [comment]
@jfroom Yes, and I have both packages excluded in my `.flowconfig` for a long time now.
Looking at this issue I wanted to give a try at removing them.
But the `type` folder does not seem to be part of the published packages, if I understand the goal of this PR well.

**Pull request merged**
