### PR TITLE
asserting undefined value

### LINKED ISSUE #111: `toHaveProp()` should maybe compare `undefined` values?
Consider a test that looks something like the following:

```jsx
class MyComponent extends React.Component {
  render () {
    return <div>{ this.props.name }</div>
  }
}

describe('MyComponent', () => {
  it('has name prop', () => {
    let props = { name: 'Mr. Foobar' }
    let wrapper = shallow(<MyComponent { ...props } />)
    expect(wrapper).toHaveProp('name', props.nameTypo)
  })
})
```

In this case, the test passes, even though there is an obvious typo in the matcher's arguments: `.toHaveProp('name', props.nameTypo)`.

The _intent_ here is obvious: the component should have a prop called `name` with a value of `'Mr. Foobar'`. In practice, though, because of the typo, the matcher simply checked that the prop existed, and stopped short of comparing the component's actual value for `name` with the expected value (of `undefined`).

I think this might be a case where the matcher _should_ have compared the values. It may be necessary to consider `arguments.length` to determine if a value comparison is required, not whether the `propValue === undefined`. Doing so should preserve the ability to call the matcher with one arg (`.toHaveProp('foo')`) as well as catch programmer mistakes like the case outlined above.

### PR DESCRIPTION
**Pull request by DianaSuvorova**
fixes #111

### CODE REVIEW

**Comment by DianaSuvorova** [comment]
@blainekasten any feedback on this?

**Comment by blainekasten** [comment]
This is awesome! Sorry for the delay. Been sick and now at a conference. Can we have a unit test at the enzyme-matcher level for this? That's where the real testing value is at for this library.

**Comment by DianaSuvorova** [comment]
@blainekasten updated 🙂

**Comment by blainekasten** [comment]
Perfect! I'll try and put out a minor release before tomorrow!

**Pull request merged**
